service: justlaunch-users
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x
  stage: ${opt:stage, 'staging'}
  timeout: 29 # defaults to maximum that API Gateway allows
  logs:
    restApi: true
  environment:
    APPLICATION_NAME: ${self:service}
    LOG_LEVEL: error
    USERS_TABLE: !Ref UsersTable
    SUPABASE_URL: https://gdhaszznbpctsygsfeej.supabase.co
    SUPABASE_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkaGFzenpuYnBjdHN5Z3NmZWVqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcxNzg4NDY3OCwiZXhwIjoyMDMzNDYwNjc4fQ.bMIrJeKQLsHYv5U_drTRVypndC2_mB50iU0_5QH4vN0
    STRIPE_API_KEY: fake-api-key
    STRIPE_WEBHOOK_KEY: fake-webhook-key

custom:
  bundle:
    excludeFiles: '**/*.test.ts'
    aliases:
      - '@usecases': src/usecases
      - '@infrastructures': src/infrastructures
      - '@interfaces': src/interfaces
      - '@domain': src/domain
      - '@utils': src/utils

functions:
  - ${file(src/interfaces/http/functions.yml)}

resources:
  #DynamoDB
  - ${file(resources/dynamodb/databases.yml)}
  # Outputs
  - ${file(resources/outputs/outputs.yml)}
